spring:
  profiles:
    active: local

---
spring:
  config:
    import: packup-submodule/application-local.yml
    activate:
      on-profile: local

---
spring:
  config:
    import: packup-submodule/application-dev.yml
    activate:
      on-profile: dev
